

spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/springtest
      username: root
      password: 123456

  redis:
      host: 127.0.0.1
      port: 6379
      password:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017
      database: springtest

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  kafka:
    consumer:
      group-id: hello-java
      auto-offset-reset: earliest
      client-id: hellojava
  main:
    banner-mode: "off"
  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: "tang:spring:session"
  mail:
    host: smtp.exmail.qq.com
    username: abc@qq.com
    password: pwd12345
    default-encoding: utf-8
  application:
    name: hello-tang

  zipkin:
    base-url: http://localhost:9000
  sleuth:
    sampler:
      percentage: 1.0

mail:
  fromMail:
    addr: abc@qq.com


app:
  datasource:
    first:
      url: jdbc:mysql://localhost:3306/springtest
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
    second:
      url: jdbc:mysql://localhost:3306/cheche2
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
# 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
# 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.qatix.hello.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    #refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    # Sequence序列接口实现类配置
    key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 1
    logic-not-delete-value: 0
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现
    meta-object-handler: com.qatix.hello.MyMetaObjectHandler

  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'
server:
  servlet:
    session:
      timeout: 3600s
